name: meetera
description: MeetEra â€“ Erasmus social companion app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.6
  google_sign_in: ^6.2.1

  # Maps & Location
  google_maps_flutter: ^2.6.0
  geocoding: ^2.2.0

  # Utilities
  http: ^1.2.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  url_launcher: ^6.3.0

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  # Media
  image_picker: ^1.0.7

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/cities.json
